import { MaterialCommunityIcons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { StyleSheet } from 'react-native-unistyles';
import { AppShell } from '@/src/components/AppShell';
import { Toggle } from '@/src/components/Toggle';
import { styles as base } from '@/src/utils/screenStyles';

const dirs = [12,1,2,3,4,5,6,7,8,9,10,11];
export default function ObserveScreen(){
  const [direction,setDirection]=useState(7); const [speech,setSpeech]=useState(true); const [announcement,setAnnouncement]=useState(true);
  return <AppShell><ScrollView style={base.screen} contentContainerStyle={styles.content}>
    <Pressable onPress={()=>router.back()} style={styles.back}><MaterialCommunityIcons name="arrow-left" size={20} color="#4B66D6"/><Text style={styles.backText}>Modes</Text></Pressable>
    <Text style={base.title}>Observe Mode</Text><Text style={[base.muted,{marginTop:5}]}>Focus X toward one direction</Text>
    <View style={styles.notice}><MaterialCommunityIcons name="information-outline" size={18} color="#7A63D8"/><Text style={styles.noticeText}>Directional listening is a hardware-level feature and is represented here for the prototype.</Text></View>
    <View style={styles.radar}><View style={styles.circle}><View style={styles.crossH}/><View style={styles.crossV}/>{dirs.map(d=>{const a=(d/12)*Math.PI*2-Math.PI/2; const left=95+Math.cos(a)*72; const top=95+Math.sin(a)*72; const selected=d===direction; return <Pressable key={d} onPress={()=>setDirection(d)} style={[styles.dir,{left:left-18,top:top-18},selected&&styles.dirSelected]}><Text style={[styles.dirText,selected&&styles.dirTextSelected]}>{d}</Text></Pressable>})}<View style={styles.center}><Text style={styles.centerText}>X</Text></View></View></View>
    <View style={base.card}><View style={styles.selectionRow}><View><Text style={styles.selectionTitle}>Listening direction</Text><Text style={base.muted}>{direction} o'clock</Text></View><MaterialCommunityIcons name="compass-outline" size={24} color="#7A63D8"/></View><View style={styles.line}/><Text style={styles.label}>Listen for</Text><SettingRow label="Speech" value={speech} onChange={setSpeech}/><SettingRow label="Announcements" value={announcement} onChange={setAnnouncement}/><SettingRow label="Environmental sound" value={false} onChange={()=>{}} disabled/></View>
    <View style={[base.card,{marginTop:14,backgroundColor:'#F7F4FF',borderColor:'#E3DBFF'}]}><Text style={styles.liveLabel}>LIVE FOCUS</Text><Text style={styles.transcriptMeta}>Focused on {direction} o'clock. Directional isolation needs the X microphone array, so no live focus stream is available in this build.</Text></View>
  </ScrollView></AppShell>
}
function SettingRow({label,value,onChange,disabled=false}:{label:string;value:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){return <View style={styles.settingRow}><Text style={[styles.settingText,disabled&&{opacity:.5}]}>{label}</Text><Toggle value={value} onChange={onChange}/></View>}
const styles=StyleSheet.create(theme=>({content:{paddingHorizontal:20,paddingTop:10,paddingBottom:110},back:{flexDirection:'row',alignItems:'center',gap:6,marginBottom:16},backText:{fontFamily:'Outfit_600SemiBold',fontSize:13,color:'#4B66D6'},notice:{marginVertical:18,backgroundColor:'#F1EEFF',borderRadius:15,padding:12,flexDirection:'row',gap:9,alignItems:'flex-start'},noticeText:{flex:1,fontFamily:'Outfit_400Regular',fontSize:11,color:'#655A95',lineHeight:17},radar:{alignItems:'center',marginBottom:22},circle:{width:190,height:190,borderRadius:95,borderWidth:1,borderColor:'#D7DADF',backgroundColor:'#FFFFFF',position:'relative',alignItems:'center',justifyContent:'center'},crossH:{position:'absolute',left:10,right:10,top:94,height:1,backgroundColor:'#E6E8E5'},crossV:{position:'absolute',top:10,bottom:10,left:94,width:1,backgroundColor:'#E6E8E5'},dir:{position:'absolute',width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:'#F1F2F0',borderWidth:1,borderColor:'#E2E4E1'},dirSelected:{backgroundColor:'#4B66D6',borderColor:'#4B66D6'},dirText:{fontFamily:'Outfit_600SemiBold',fontSize:10,color:theme.colors.textMuted},dirTextSelected:{color:'#FFFFFF'},center:{width:54,height:54,borderRadius:27,backgroundColor:'#EEF1FF',alignItems:'center',justifyContent:'center'},centerText:{fontFamily:'Outfit_800ExtraBold',fontSize:22,color:'#4B66D6'},selectionRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},selectionTitle:{fontFamily:'Outfit_600SemiBold',fontSize:14,color:theme.colors.text,marginBottom:3},line:{height:1,backgroundColor:theme.colors.border,marginVertical:13},label:{fontFamily:'Outfit_600SemiBold',fontSize:11,color:theme.colors.text,marginBottom:5},settingRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingVertical:8},settingText:{fontFamily:'Outfit_500Medium',fontSize:12,color:theme.colors.text},liveLabel:{fontFamily:'Outfit_700Bold',fontSize:10,color:'#7A63D8',letterSpacing:1},transcript:{fontFamily:'Outfit_600SemiBold',fontSize:15,color:theme.colors.text,lineHeight:22,marginTop:7},transcriptMeta:{fontFamily:'Outfit_400Regular',fontSize:10,color:theme.colors.textMuted,marginTop:7} }));
