import { MaterialCommunityIcons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { RefreshControl, ScrollView, Text, View, Pressable } from 'react-native';
import { StyleSheet } from 'react-native-unistyles';
import { AppShell } from '@/src/components/AppShell';
import { useApp } from '@/src/state/AppContext';
import { styles as base } from '@/src/utils/screenStyles';

export default function DeviceScreen() {
  const { device, analytics, refreshing, refreshAll } = useApp();
  const battery = device?.battery ?? 0;
  return <AppShell><ScrollView style={base.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refreshAll}/>}><View style={base.headerRow}><View><Text style={base.brand}>X Device</Text><Text style={base.eyebrow}>Device health and activity</Text></View><View style={styles.online}><View style={styles.onlineDot}/><Text style={styles.onlineText}>{device?.connected === false ? 'Offline' : 'Connected'}</Text></View></View>
    <View style={styles.hero}><View style={styles.heroIcon}><MaterialCommunityIcons name="watch-variant" size={29} color="#4B66D6"/></View><View style={{flex:1}}><Text style={styles.heroTitle}>X Wearable</Text><Text style={base.muted}>Ready to receive configuration and events.</Text></View></View>
    <Text style={base.sectionTitle}>Battery</Text><View style={base.card}><View style={styles.batteryRow}><Text style={styles.batteryPercent}>{device ? `${battery}%` : '—'}</Text><Text style={styles.batteryStatus}>{device?.charging ? 'Charging' : 'Not charging'}</Text></View><View style={styles.batteryTrack}><View style={[styles.batteryFill,{width:`${battery}%`}]}/></View><View style={styles.chargingPreview}><MaterialCommunityIcons name={device?.charging ? 'battery-charging' : 'battery-outline'} size={17} color="#4B66D6"/><Text style={styles.chargingText}>Reported by the X device over PATCH /api/v1/device</Text></View></View>
    <Text style={[base.sectionTitle,{marginTop:22}]}>Device Status</Text><View style={base.card}><StatusRow label="Connection" value={device?.connected === false ? 'Disconnected' : 'Connected'} icon="bluetooth"/><StatusRow label="Bluetooth" value={device?.bluetooth ?? 'Connected'} icon="bluetooth-connect"/><StatusRow label="Microphones" value={device?.microphones ?? 'Active'} icon="microphone-outline"/><StatusRow label="Sensors" value={device?.sensors ?? 'Active'} icon="motion-sensor"/><StatusRow label="Firmware" value={device?.firmware ?? 'Up to date'} icon="update"/></View>
    <Text style={[base.sectionTitle,{marginTop:22}]}>Analytics</Text><Pressable onPress={() => router.push('/analytics')} style={[base.card,styles.analyticsCard]}><View style={styles.analyticsIcon}><MaterialCommunityIcons name="chart-box-outline" size={21} color="#7A63D8"/></View><View style={{flex:1}}><Text style={styles.analyticsTitle}>Sound activity</Text><Text style={base.muted}>{analytics?.total ?? 0} detected events · {analytics?.today ?? 0} today · {analytics?.critical ?? 0} critical</Text></View><MaterialCommunityIcons name="chevron-right" size={20} color="#9CA19D"/></Pressable>
    <Text style={styles.note}>Notifications for X status and charging are shown here without requiring any physical hardware in the demo.</Text>
  </ScrollView></AppShell>;
}
function StatusRow({label,value,icon}:{label:string;value:string;icon:keyof typeof MaterialCommunityIcons.glyphMap}){return <View style={styles.statusRow}><MaterialCommunityIcons name={icon} size={18} color="#4B66D6"/><Text style={styles.statusLabel}>{label}</Text><Text style={styles.statusValue}>{value}</Text></View>}
const styles=StyleSheet.create((theme)=>({content:{paddingHorizontal:20,paddingTop:10,paddingBottom:110},online:{flexDirection:'row',alignItems:'center',gap:6,backgroundColor:'#EEF7F1',paddingHorizontal:10,paddingVertical:7,borderRadius:999},onlineDot:{width:7,height:7,borderRadius:4,backgroundColor:theme.colors.success},onlineText:{fontFamily:'Outfit_600SemiBold',fontSize:10,color:'#2F7B53'},hero:{backgroundColor:'#EEF1FF',borderRadius:20,padding:16,flexDirection:'row',alignItems:'center',gap:12,marginBottom:22},heroIcon:{width:54,height:54,borderRadius:17,backgroundColor:'#FFFFFF',alignItems:'center',justifyContent:'center'},heroTitle:{fontFamily:'Outfit_700Bold',fontSize:19,color:theme.colors.text,marginBottom:3},batteryRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},batteryPercent:{fontFamily:'Outfit_700Bold',fontSize:30,color:theme.colors.text},batteryStatus:{fontFamily:'Outfit_500Medium',fontSize:12,color:theme.colors.textMuted},batteryTrack:{height:10,borderRadius:5,backgroundColor:'#E8EAE7',overflow:'hidden',marginTop:12},batteryFill:{height:'100%',backgroundColor:'#4B66D6',borderRadius:5},chargingPreview:{flexDirection:'row',alignItems:'center',gap:8,marginTop:15,paddingTop:13,borderTopWidth:1,borderTopColor:theme.colors.border},chargingText:{fontFamily:'Outfit_500Medium',fontSize:11,color:'#4B66D6'},statusRow:{flexDirection:'row',alignItems:'center',paddingVertical:11,gap:10,borderBottomWidth:1,borderBottomColor:theme.colors.border},statusLabel:{fontFamily:'Outfit_400Regular',fontSize:12,color:theme.colors.textMuted,flex:1},statusValue:{fontFamily:'Outfit_600SemiBold',fontSize:12,color:theme.colors.text},analyticsCard:{flexDirection:'row',alignItems:'center',gap:11,paddingVertical:14},analyticsIcon:{width:42,height:42,borderRadius:13,backgroundColor:'#F1EEFF',alignItems:'center',justifyContent:'center'},analyticsTitle:{fontFamily:'Outfit_600SemiBold',fontSize:14,color:theme.colors.text,marginBottom:3},note:{fontFamily:'Outfit_400Regular',fontSize:11,color:theme.colors.textMuted,lineHeight:17,marginTop:15} }));
